### ISSUE TITLE
vote.js createVote function fails due to join issue

### ISSUE THREAD

**Issue by Isabello** [blockpool-io/BPL-js#4]
```
readline.js:982
            throw err;
            ^

TypeError: Cannot read property 'join' of undefined
    at getBytes (/home/lisk/bpl-client/node_modules/bpljs/lib/transactions/crypto.js:50:52)
    at getHash (/home/lisk/bpl-client/node_modules/bpljs/lib/transactions/crypto.js:161:44)
    at Object.sign (/home/lisk/bpl-client/node_modules/bpljs/lib/transactions/crypto.js:185:13)
    at Object.createVote (/home/lisk/bpl-client/node_modules/bpljs/lib/transactions/vote.js:20:9)
    at /home/lisk/bpl-client/index.js:399:38
    at nextTask (/home/lisk/bpl-client/node_modules/async/dist/async.js:5297:14)
    at next (/home/lisk/bpl-client/node_modules/async/dist/async.js:5304:9)
    at /home/lisk/bpl-client/node_modules/async/dist/async.js:906:16
    at /home/lisk/bpl-client/index.js:390:20
    at cb (/home/lisk/bpl-client/node_modules/vorpal/dist/vorpal.js:552:9)
```

This is from bpl-client, after fixing the line for createVote on line 399

**Comment by cyrus19901** [comment]
We are looking into the error here

**Comment by cyrus19901** [comment]
This issue was in BPL-client which has been taken care of.
